In [18]:
import torch
import numpy as np

## Basic  Operation

In [2]:
x = torch.empty(2,2,2)
print(x)

tensor([[[7.2053e+22, 4.7428e+30],
         [8.1717e-07, 5.8270e-10]],

        [[5.8270e-10, 8.2990e-33],
         [1.3563e-19, 1.3563e-19]]])


In [3]:
x = torch.rand(2,2)
print(x)

tensor([[0.7738, 0.9816],
        [0.0931, 0.1668]])


In [4]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [6]:
# Set dtype for tensor
x = torch.ones(2,2, dtype= torch.double)
print(x.dtype)
print(x.size())

torch.float64
torch.Size([2, 2])


In [7]:
# Change a list into tensor
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


## Tensor Operation

In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x+y
# z = torch.add(x,y)
print(z)

tensor([[0.7065, 0.4410],
        [0.6842, 0.9136]])
tensor([[0.5884, 0.0913],
        [0.6343, 0.3313]])
tensor([[1.2949, 0.5323],
        [1.3185, 1.2449]])


In [9]:
# Inplace addition
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
y.add_(x) # _ means that it will inplace value y
print(y)

tensor([[0.8858, 0.6540],
        [0.3338, 0.8576]])
tensor([[0.2211, 0.4213],
        [0.3886, 0.6042]])
tensor([[1.1069, 1.0753],
        [0.7224, 1.4617]])


In [10]:
# z = x-y
# z = x*y
# z = x/y
# z = torch.sub(x,y)
# z = torch.mul(x,y)
# z = torch.div(x,y)
# y.mul_(x)

In [11]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[1,:])
print(x[0,0].item()) # Retrieve just the value

tensor([[0.6895, 0.8818, 0.2254],
        [0.8299, 0.8791, 0.7938],
        [0.0658, 0.4414, 0.1948],
        [0.4403, 0.9843, 0.8490],
        [0.7348, 0.5038, 0.8655]])
tensor([0.8299, 0.8791, 0.7938])
0.6894978880882263


## Reshape Tensor

In [13]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
print(y.size())

tensor([[0.6697, 0.4316, 0.9252, 0.8920],
        [0.2955, 0.1844, 0.9034, 0.1358],
        [0.9272, 0.0193, 0.6365, 0.3529],
        [0.7603, 0.1532, 0.5153, 0.7514]])
tensor([0.6697, 0.4316, 0.9252, 0.8920, 0.2955, 0.1844, 0.9034, 0.1358, 0.9272,
        0.0193, 0.6365, 0.3529, 0.7603, 0.1532, 0.5153, 0.7514])
torch.Size([16])


In [14]:
x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.2454, 0.5121, 0.3840, 0.8749],
        [0.9168, 0.4943, 0.4310, 0.5937],
        [0.3403, 0.7863, 0.6506, 0.5392],
        [0.2208, 0.9780, 0.5805, 0.6819]])
tensor([[0.2454, 0.5121, 0.3840, 0.8749, 0.9168, 0.4943, 0.4310, 0.5937],
        [0.3403, 0.7863, 0.6506, 0.5392, 0.2208, 0.9780, 0.5805, 0.6819]])
torch.Size([2, 8])


## tensor to numpy.ndarray

In [16]:
a = torch.ones(5)
print(a)
print(type(a))

# Change tensor into numpy.ndarray
b = a.numpy()
print(type(b))


'''
Cautious !
If they run in CPU, that means they share same memory location, so if you change 'a' values, b would also change !
'''

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


"\nCautious !\nIf they run in CPU, that means they share same memory location, so if you change 'a' values, b would also change !\n"

In [19]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## Checking GPU and Switching GPU to CPU (viceversa)

In [22]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device) # Operation in GPU
    y = torch.ones(5)
    y = y.to(device) # Operation in GPU
    z = x+y # Operation in GPU
    #z.numpy() # Will get error, because only handle CPU tensor
    # First convert it into CPU
    z = z.to('cpu')

## Set gradient

In [21]:
# Allow to calculate gradient for this tensor in optimization step
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
