In [1]:
import torch

## Calculate Gradient

In [9]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)

z = y*y*2
print(z)

z = z.mean()
print(z)

# Calculate the gradient
z.backward() # dz/dx
print(x.grad)

tensor([1.3924, 0.2586, 0.8945], requires_grad=True)
tensor([3.3924, 2.2586, 2.8945], grad_fn=<AddBackward0>)
tensor([23.0167, 10.2027, 16.7561], grad_fn=<MulBackward0>)
tensor(16.6585, grad_fn=<MeanBackward0>)
tensor([4.5232, 3.0115, 3.8593])


## If the input are not scalar

In [21]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)

z = y*y*2
print(z)

# Because backward is Vector Jacobian Product, you need a vector ! 
v = torch.tensor([0.1,1.0,0.001], dtype = torch.float32)

# Calculate the gradient
z.backward(v) # dz/dx
print(x.grad)

tensor([-0.4339, -0.5421,  0.3699], requires_grad=True)
tensor([1.5661, 1.4579, 2.3699], grad_fn=<AddBackward0>)
tensor([ 4.9052,  4.2510, 11.2332], grad_fn=<MulBackward0>)
tensor([0.6264, 5.8317, 0.0095])


## 3 Ways to prevent for tracking the gradients

```python
1. x.requires_grad_(False) # Inplacing the gradient to false
2. x.detach() # Create new tensor that doesn't required the gradient
3. with torch.no_grad(): 
    pass
```

In [22]:
print(x)

# Prevent the gradient to calculate
v = x.detach()
b = x.requires_grad_(False)
# x.requires_grad_(False)

print(b)
print(v)

# Prevent the gradient to calculate
with torch.no_grad():
    g = y+2
    print(g)

# Still calculate the gradient
g = y+2 
print(g)

tensor([-0.4339, -0.5421,  0.3699], requires_grad=True)
tensor([-0.4339, -0.5421,  0.3699])
tensor([-0.4339, -0.5421,  0.3699])
tensor([3.5661, 3.4579, 4.3699])
tensor([3.5661, 3.4579, 4.3699], grad_fn=<AddBackward0>)


## grad in looping

In [25]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    print(weights.grad)
    
    #weights.grad.zero_() # You need to re-assgin to zero
    #print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


## Backpropagation

In [31]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w * x
loss = (y_hat-y)**2

print(loss)

# backward pass
loss.backward()
print(w.grad)

## update weights
## next forwards and backwards

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
